### ISSUE TITLE
NyroModal issue with jquery 1.8.1

### ISSUE THREAD

**Issue by bpmn** [nyroDev/nyroModal#189]
Since I upgraded the jquery version from 1.7.2 to 1.8.1, there is a script error when calling nyromodal function.

TypeError: $.curCSS is not a function

**Comment by bpmn** [comment]
ok fixed by replacing curCSS by css in the code..
